AWSTemplateFormatVersion: 2010-09-09
Description: IAM role for Glue (least privilege) – bucket exists already.

Parameters:
  Environment:
    Type: String
    Default: dev
  Prefix:
    Type: String
    Default: lead
  ExistingBucketName:
    Type: String
    Description: Name of an existing S3 bucket (required)
  ApiSecretName:
    Type: String
    Default: api_key_closeio-dev

Resources:
  GlueJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Prefix}-glue-job-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: glue.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Path: "/"

  GlueJobAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${Prefix}-glue-job-inline-${Environment}"
      Roles: [ !Ref GlueJobRole ]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: S3BucketLevel
            Effect: Allow
            Action: [ "s3:ListBucket", "s3:GetBucketLocation" ]
            Resource: !Sub "arn:aws:s3:::${ExistingBucketName}"
          - Sid: S3ObjectLevel
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:AbortMultipartUpload
              - s3:ListBucketMultipartUploads
              - s3:ListMultipartUploadParts
            Resource: !Sub "arn:aws:s3:::${ExistingBucketName}/*"
          - Sid: ReadCloseApiSecret
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${ApiSecretName}*"
          - Sid: KmsDecryptViaSM
            Effect: Allow
            Action: kms:Decrypt
            Resource: "*"
            Condition:
              StringEquals:
                kms:ViaService: !Sub "secretsmanager.${AWS::Region}.amazonaws.com"

Outputs:
  GlueJobRoleArn:
    Value: !GetAtt GlueJobRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GlueJobRoleArn"
