AWSTemplateFormatVersion: 2010-09-09
Description: Secrets Manager secret for an external API key

Parameters:
  Environment:
    Type: String
    Default: dev
  Prefix:
    Type: String
    Default: lead
  ApiKeyValue:
    Type: String
    NoEcho: true
    Description: The API key value to store securely in Secrets Manager
  SecretName:
    Type: String
    Default: api_key_closeio
    Description: Base name for the secret (env will be appended)

Resources:
  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${SecretName}-${Environment}"
      Description: !Sub "External API key for ${SecretName} (${Environment})"
      SecretString: !Sub |
        {
          "api_key": "${pi_0vDMSu1OitLWCjbtX3Gvdw.7RHFotMMC01tkWE9uq359X}"
        }
      Tags:
        - Key: Name
          Value: !Sub "${Prefix}-${SecretName}-${Environment}"

Outputs:
  ApiKeySecretArn:
    Description: ARN of the API key secret
    Value: !Ref ApiKeySecret
    Export:
      Name: !Sub "${AWS::StackName}-ApiKeySecretArn"
