AWSTemplateFormatVersion: 2010-09-09
Description: "Glue job to ingest Close leads/activities and write to S3 (JSON/Parquet)."

Parameters:
  Prefix:
    Type: String
    Default: lead
    Description: "Name prefix for resources (e.g., 'lead')."

  Environment:
    Type: String
    Default: dev
    Description: "Deployment environment (e.g., dev/prod)."

  S3Bucket:
    Type: String
    Description: "Existing S3 bucket name that holds scripts and receives output."

  GlueJobRoleArn:
    Type: String
    Description: "IAM role ARN for the Glue job."

  ApiSecretArn:
    Type: String
    Description: "Secrets Manager ARN or name holding {\"api_key\":\"...\"}."

  ApiBaseUrl:
    Type: String
    Default: https://api.close.com/api/v1
    Description: "Base URL for Close API."

  OutputFormat:
    Type: String
    Default: parquet
    AllowedValues: [parquet, json]
    Description: "Output format to write to S3 (parquet|json)."

  PageSize:
    Type: Number
    Default: 200
    Description: "Page size for Close search."

  MaxPages:
    Type: Number
    Default: 500
    Description: "Safety cap on pages per search."

  FetchLeadDetails:
    Type: String
    Default: "false"
    AllowedValues: ["true","false"]
    Description: "Whether to fetch per-lead detail documents."

  StartDate:
    Type: String
    Default: ""
    Description: "Optional inclusive start date (YYYY-MM-DD). Leave empty for yesterday."

  EndDate:
    Type: String
    Default: ""
    Description: "Optional inclusive end date (YYYY-MM-DD). Leave empty for today."

  LeadLimit:
    Type: Number
    Default: 0
    Description: "Optional cap on number of leads processed (0 = no cap)."

Resources:
  CloseIngestJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub "${Prefix}-closeio-ingest-${Environment}"
      Role: !Ref GlueJobRoleArn
      GlueVersion: "4.0"
      NumberOfWorkers: 2
      WorkerType: G.1X
      Command:
        Name: glueetl
        PythonVersion: 3
        ScriptLocation: !Sub "s3://${S3Bucket}/scripts/closeio_ingest_glue.py"
      DefaultArguments:
        "--job-language": "python"
        "--enable-glue-datacatalog": "true"
        "--enable-continuous-cloudwatch-log": "true"
        "--enable-metrics": "true"
        "--TempDir": !Sub "s3://${S3Bucket}/temp/"

        # app args (your Glue script reads these via getResolvedOptions)
        "--SECRET_ID": !Ref ApiSecretArn
        "--API_BASE_URL": !Ref ApiBaseUrl
        "--S3_OUTPUT":  !Sub "s3://${S3Bucket}/landing/closeio/"
        "--OUTPUT_FORMAT": !Ref OutputFormat
        "--PAGE_SIZE": !Ref PageSize
        "--MAX_PAGES": !Ref MaxPages
        "--FETCH_LEAD_DETAILS": !Ref FetchLeadDetails
        "--START_DATE": !Ref StartDate
        "--END_DATE": !Ref EndDate
        "--LEAD_LIMIT": !Ref LeadLimit

        # job bookmarks don’t apply for REST pulls; keep disabled
        "--job-bookmark-option": "job-bookmark-disable"

Outputs:
  CloseIngestJobName:
    Description: "Glue job name."
    Value: !Ref CloseIngestJob
